name = 'Zero Academic Page'
license = 'GPL-3.0'
licenselink = 'https://github.com/geekifan/zero-academic-page/LICENSE'
description = 'A simple but modern academic page theme for researchers'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/geekifan/zero-academic-page'

# If you have a running demo of the theme
demosite = 'https://geekifan.github.io/zero-academic-page'

# If the theme has multiple authors
authors = [
  {name = 'Yifan', homepage = 'https://github.com/geekifan'},
  {name = 'Ruopeng', homepage = 'https://github.com/HELLORPG'}
]
