[en]
languageName = 'English'
weight = 1
title = 'Zero'

[en.params]
    author = "Lorem ipsum"
    description = "Ph.D Student in [Lorem ipsum College](https://example.com). Focusing on Computer Vision and Deep Learning."
    motto = "Most things in the world are not that important. But truth and love matter."

[[en.menu.main]]
    name = 'About Me'
    url = '#about-me'
    weight = 1
[[en.menu.main]]
    name = 'News'
    url = '#news'
    weight = 2
[[en.menu.main]]
    name = 'Publications'
    url = '#publications'
    weight = 3
[[en.menu.main]]
    name = 'Honors and Awards'
    url = '#honors-and-awards'
    weight = 4
[[en.menu.main]]
    name = 'Educations'
    url = '#educations'
    weight = 5
[[en.menu.main]]
    name = 'Invited Talks'
    url = '#invited-talks'
    weight = 6
[[en.menu.main]]
    name = 'Internships'
    url = '#internships'
    weight = 7
    
[zh]
languageName = '中文'
weight = 2
title = '学术主页'

[zh.params]
    author = "王小明"
    description = "某某大学博士生，专注于计算机视觉与深度学习"
    motto = "世界上大部分事，都没有太大意义。真理与爱除外。"

[[zh.menu.main]]
    name = '关于我'
    url = '#about-me'
    weight = 1
[[zh.menu.main]]
    name = '新闻'
    url = '#news'
    weight = 2
[[zh.menu.main]]
    name = '发表论文'
    url = '#publications'
    weight = 3
[[zh.menu.main]]
    name = '荣誉与奖项'
    url = '#honors-and-awards'
    weight = 4
[[zh.menu.main]]
    name = '教育背景'
    url = '#educations'
    weight = 5
[[zh.menu.main]]
    name = '受邀报告'
    url = '#invited-talks'
    weight = 6
[[zh.menu.main]]
    name = '实习经历'
    url = '#internships'
    weight = 7